### ISSUE TITLE
MSE metric uses whole image instead of completed pixels

### ISSUE THREAD

**Issue by jostosh** [jhonatanoliveira/dcspns#1]
First of all, thank you for your interesting work and for the release of your code!

I believe that to fairly compare your results against those obtained in [Poon and Domingos (2011)](http://ai.cs.washington.edu/www/media/papers/tmp5_6MRm.pdf), you would need to compute the MSE on only the completed pixels. Quoting from that article:
> We report mean square errors of the completed pixels of
test images for these five algorithms.

The source code from Poon and Domingos clearly iterates over **half** of the pixels for one dimension (notice the `size/2`):
```java
while ((s=in.readLine())!=null) {
	idx++;			
	if (idx==size+padLen) {
		idx=0;
	}
	else if (idx>size) {
		continue;
	}
	else {
		String[] ts=s.split(",");
		for (int i=0; i<size/2; i++) {
			double q1=Double.parseDouble(ts[i]), q2=Double.parseDouble(ts[i+size+padLen]);
			p+=(q1-q2)*(q1-q2);
			c++;
		}
	}
}
```

Your current code seems to compute the MSE on the _whole image_ (including the pixels that are already given). This means that the squared error of half of your pixels is exactly 0, thus resulting in MSEs on the _completed_ pixels that would actually be twice as high if computed correctly.

Please correct me if I'm wrong.

**Comment by jhonatanoliveira** [comment]
Dear Jos,

Thank you for your message. Yes, you are right. Our implementation did not compute MSE correctly. We have fixed our code. Thank you.

In our AAAI 2019 paper, the MSE scores reported for DCSPNs and DCGANs should be doubled. We apologize for this misunderstanding.
